config/routes.rb
Rails.application.routes.draw do
  resources :categories
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  #metodo 'ruta', to 'controlador#accion'
  get 'bienvenida', to: "home#index"

  root to: "home#index"

  # get 'articles', to: "articles#index"
  # get 'articles/new', to: "articles#new", as: :new_articles # esto se resume como new_article_path, sin la s, cambiarlo en el html
  # post 'articles', to: "articles#create"
  # get 'articles/:id', to: 'articles#show'
  # get 'articles/:id/edit', to: 'articles#edit'
  # patch 'articles/:id', to: 'articles#update', as: :article
  # delete 'articles/:id', to: 'articles#destroy'
  # get 'articles/user/:user_id', to: "articles#from_author"
  # todo esto se resume en
  resources :articles do
    get 'user/:user_id', to: "articles#from_author", on: :collection
  end
  
  devise_for :users
  get 'profile', to: "users#edit"
  resources :users, only:[:update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_rich_text :content
  belongs_to :user #campo adicional user_id
  has_many :has_categories
  has_many :categories, through: :has_categories
  attr_accessor :category_elements

  def save_categories
    # si recibe un string 1,2,3
    # convertir a array
    # categories_array = category_elements.split(",")
    # al hacer checkbox ya viene como arreglo
    # Si esta vacio borro todas
    return has_categories.destroy_all if category_elements.nil? || category_elements.empty?
    # Borro las no seleccionadas
    has_categories.where.not(category_id: category_elements).destroy_all
    # Itero y agrego las seleccionadas
    category_elements.each do |category_id|
      # unless HasCategory.where(article: self, category_id: category_id).any?
      #   HasCategory.create(article: self, category_id: category_id)
      # end
      # o mejor
      HasCategory.find_or_create_by(article: self, category_id: category_id)
    end
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :has_categories
  has_many :articles, through: :has_categories
end

app/models/has_category.rb
class HasCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :articles
  has_one_attached :avatar
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :find_article, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
    # declarando con @ se puede aceder desde la vista
    @article.title = 'Demo'
    @categories = Category.all
  end

  def create
    # @article = Article.create(title: params[:article][:title], # recibir datos del formulario
    #                           content: params[:article][:content],
    #                           user: current_user) # el create debe estar protegido por auth
    # otra forma, accediendo desde la coleccion de articulos del usuario
    # @article = current_user.articles.create(title: params[:article][:title],
    #                                         content: params[:article][:content])
    # refactor para especificar lso params aparte
    @article = current_user.articles.create(article_params)
    @article.save_categories
    redirect_to @article # mostrar 
  end

  def show
  end

  def edit
    @categories = Category.all
  end

  def update
    @article.update(article_params)
    @article.save_categories
    redirect_to @article
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  def from_author
    @user = User.find(params[:user_id])
  end

  def find_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :content, category_elements: [])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %w[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:title, :color)
    end
end

app/controllers/home_controller.rb
# file name in snake_case and class name in PascalCase
# class must be a subclass of ApplicationController in order to be a controller
class HomeController < ApplicationController
  before_action :authenticate_user!
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  skip_before_action :authorized, only: [:new, :create, :welcome]

  def new
  end

  def create
    @user = User.find_by(username: params[:username])
    if @user && @user.authenticate(params[:password])
       sessions[:user_id] = @user.id
       redirect_to '/welcome'
    else
       redirect_to '/login'
    end
  end

  def login
  end

  def welcome
  end

  def page_requires_login
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def edit
  end
  def update
    current_user.update(user_params)
    redirect_back(fallback_location: root_path)
  end
  def user_params
    params.require(:user).permit(:avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/articles/_article.html.erb
<div class="card padding margin-top">
  <h5 class="text-uppercase"><%= article.id %>. <%= article.title %></h5>
  <p class="small text-secondary"> 
    created: <%= article.created_at %>
  </p>
  <%=link_to "Ver", article %>
</div>

app/views/articles/_form.html.erb
<%= form_with(model: @article, local: true) do |form| %> 
<!-- local true para que no mande por ajax -->
  <div class="field">
    <%=form.label :title %>
    <%=form.text_field :title %>
  </div>
  <div class="field">
    <%=form.label :category_elements %>
    <div class="row">
      <% @categories.each do |category| %>
        <label class="col-6 col-sm-4">
          <%= form.check_box :category_elements, {multiple: true}, category.id, nil%>
          <%= category.title %>
        </label>
      <%end%>
    </div>
  </div>
  <div class="field">
    <%=form.label :content %>
    <%=form.rich_text_area :content %>
  </div>
  <div>
    <%=form.submit %>
  </div>
<%end%>

app/views/articles/edit.html.erb
<div class="small-container center-block">
  <h3>Edit Article <%:title%></h3>
  <%= render "articles/form" %>
</div>

app/views/articles/from_author.html.erb
<div class="large-container center-block">
  <h3>Articles from <%= @user.email %></h3>
  <%= render @user.articles %>
</div>

app/views/articles/index.html.erb
<div class="large-container center-block">
<h3>Articles</h3>
<!--
<% @articles.each do |article| %> sin el = para que no se imprima la coleccion raw
  aca mostrar el articulo
<% end %> -->
<%= render @articles %>
</div>

app/views/articles/new.html.erb
<div class="small-container center-block">
  <h3>New Article</h3>
  <%= render "articles/form" %>
</div>

app/views/articles/show.html.erb
<div class="small-container center-block">
  <h1 class="text-uppercase"><%=@article.title %></h1>
  <h3 class="small text-secondary"> 
    by <strong><%=@article.user.email %></strong>,
    <%= @article.created_at %>
  </h3>
  
  <div class="padding">
    <%=@article.content %>
  </div>

  <div class="margin-top">
    <p class="label">Tags</p>
    <% @article.categories.each do |category| %>
      <span class="badge badge-pill padding"
            style="background-color:<%= category.color %>">
        <%= link_to category.title, category, class:"text-white" %>
      </span>
    <%end%>
  </div>
  <div class="margin-top">
    <%=link_to "Edit", controller: "articles", action: "edit", id: @article %>
    <%=link_to "Delete", @article, method: "delete" %>
    <%=link_to "Back", :back %>
  </div>
</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :color %>
    <%= form.color_field :color %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<div class="small-container center-block">
  <h1>Editing Category</h1>

  <%= render 'form', category: @category %>

  <%= link_to 'Show', @category %> |
  <%= link_to 'Back', categories_path %>
</div>

app/views/categories/index.html.erb
<div class="large-container center-block">
  <p id="notice"><%= notice %></p>

  <h1>Categories</h1>

  <table>
    <thead>
      <tr>
        <th>Title</th>
        <th>Color</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @categories.each do |category| %>
        <tr>
          <td><%= category.title %></td>
          <td><%= category.color %></td>
          <td><%= link_to 'Show', category %></td>
          <td><%= link_to 'Edit', edit_category_path(category) %></td>
          <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Category', new_category_path %>
</div>

app/views/categories/new.html.erb
<div class="small-container center-block">
  <h1>New Category</h1>

  <%= render 'form', category: @category %>

  <%= link_to 'Back', categories_path %>
</div>

app/views/categories/show.html.erb
<div class="small-container center-block">
  <p>
    <strong>Title:</strong>
    <span class="badge badge-pill text-white padding"
          style="background-color:<%= @category.color %>">
      <%= @category.title %>
    </span>
  </p>
  <p>
    <strong>Color:</strong>
    <%= @category.color %>
  </p>

  <%= link_to 'Edit', edit_category_path(@category) %> |
  <%= link_to 'Back', categories_path %>

  <p>
    <strong>Articles:</strong>
  </p>
  <%= render @category.articles %>
</div>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%=render "partials/nav" %>
    <%if notice %>
      <p class="alert alert-info"><%= notice %></p>
    <%end%>
    <%if alert %>
    <p class="alert alert-danger"><%= alert %></p>
    <%end%>

    <%= yield %>

  </body>
</html>

app/views/partials/_nav.html.erb
<nav class="nav bg-dark padding">
  <li class="nav-item">
    <%=link_to "Home", root_path, class:"nav-link" %>
  </li>
  <li class="nav-item">
    <%=link_to "Categories", categories_path, class:"nav-link" %>
  </li>
  <li class="nav-item">
    <%=link_to "Articles", articles_path, class:"nav-link" %>
  </li>

  <%if user_signed_in?%>
    <li class="nav-item">
      <%=link_to "New", new_article_path, class:"nav-link" %>
    </li>
    <li class="nav-item">
      <span class="nav-link"> welcome, <%= current_user.email %>! </span>
    </li>
    <li class="nav-item">
      <%=link_to "Profile", profile_path, class:"nav-link" %>
    </li>
    <li class="nav-item">
      <%=link_to "Logout", destroy_user_session_path, method: :delete, class:"nav-link" %>
    </li>
  <% else %>
    <li class="nav-item">
      <%=link_to "Login", new_user_session_path, class:"nav-link" %>
    </li>
    <li class="nav-item">
      <%=link_to "Sign Up", new_user_registration_path, class:"nav-link" %>
    </li>
  <%end%>
</nav>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/edit.html.erb
<div class="small-container center-block">
  <h1 class="font-weight-bold text-uppercase margin-top">Edit Profile</h1>
  <% if current_user.avatar.attached? %>
    <%= image_tag url_for(current_user.avatar), height:200 %>
  <%end%>
  <%= form_with(model: current_user, local: true) do |form| %>
    <div class="field">
      <%= form.label :avatar %>
      <%= form.file_field :avatar %>
    </div>
    <div class="field">
      <%= form.submit %>
    </div>
  <%end%>
</div>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= form_for @user do |f|%>
  <%= f.label :username%><br>
  <%= f.text_field :username%><br>
  <%= f.label :password%><br>
  <%= f.password_field :password%><br>
  <%= f.submit %>
<%end%>